### ISSUE TITLE
Make a package?

### ISSUE THREAD

**Issue by rafaqueque** [f-prime/Hey#2]
Hi there, 

Love the concept. Any possibility to wrap that into a nice package to be installed with `pip` or even `brew`?

**Comment by f-prime** [comment]
I like that idea, I will do that.

**Comment by f-prime** [comment]
There, I made a Pypi package.

**Comment by rafaqueque** [comment]
Good to know, thanks.

On Wed, Jul 30, 2014 at 10:54 PM, Frankie Primerano <
notifications@github.com> wrote:

> There, I made a Pypi package.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Max00355/Hey/issues/2#issuecomment-50685717.

## 

Rafael Albuquerque,
http://rafael.pt
