### ISSUE TITLE
Crash on google keyword

### ISSUE THREAD

**Issue by vaz-ar** [f-prime/Hey#4]
`» hey google "How awesome is Python?" for me, thanks.`

Traceback (most recent call last):
  File "/home/Arnaud/scripts/modules/Hey/hey", line 54, in <module>
    Hey().parse()
  File "/home/Arnaud/scripts/modules/Hey/hey", line 46, in parse
    self.keywords[x](' '.join(string))
  File "/cygdrive/c/Users/Arnaud/HERE/Projets/scripts_-_co/modules/Hey/google.py", line 6, in google
    webbrowser.open("https://www.google.com/search?q={}".format(data[0]))
IndexError: list index out of range

This seems to happen because double quotes are stripped when passed to the python script. If you display the content of sys.argv in Hey().parse(), you get `['/home/Arnaud/scripts/modules/Hey/hey', 'google', 'How awesome is Python?', 'for', 'me,', 'thanks.']`

Did you happen to run into the same problem ?

**Comment by DanielAndreasen** [comment]
I have the same problem. Also tried

`./hey google test`

But with the same result

**Comment by f-prime** [comment]
Yes, this is a very simple fix. Assuming that you are on Mac or Linux in the terminal you have to escape the quotes so your command has to actually look something like this: 

```
./hey google \"How awesome is Python?\"
```

**Comment by DanielAndreasen** [comment]
Yes, that works, but maybe a workaround or an update in the README? :)

**Comment by f-prime** [comment]
I do like the idea of quotes so I will just update the readme :)

**Comment by vaz-ar** [comment]
Why not remove the quotes ? it is uneasy to have to escape quotes every time.

**Comment by f-prime** [comment]
Honestly, it makes it easier to parse and makes compound commands (something I am working on now) easier to deal with.
